/**
 * 
 * @module Enums
 * 
 * @preferred
 * 
 * @description Module for enums types defined in SenseNet helps you to use enums with dot notation. 
 *
 * This module is autogenerated from Sense/Net metadata (/Odata/$metadata)
 *
 * ```
 * let car = new ContentTypes.Car({
 *  Id: 1,
 *  Name: 'MyCar',
 *  DisplayName: 'My Car',
 *  Style: Enum.Style.Cabrio
 * });
 * ```
 */ /** */

    export enum VersioningMode { Option0, Option1, Option2, Option3 }
    export enum InheritableVersioningMode { Option0, Option1, Option2, Option3 }
    export enum ApprovingMode { Option0, Option1, Option2 }
    export enum InheritableApprovingMode { Option0, Option1, Option2 }
    export enum SavingState { Finalized, Creating, Modifying, ModifyingLocked }
    export enum GroupAttachments { email, root, subject, sender }
    export enum EnableAutofilters { Default, Enabled, Disabled }
    export enum EnableLifespanFilter { Default, Enabled, Disabled }
    export enum Language { En, Hu }
    export enum MemoType { generic, iso, iaudit }
    export enum Priority { Option0, Option1, Option2 }
    export enum Status { pending, active, completed, deferred, waiting }
    export enum QueryType { Public, Private }
    export enum Gender { Option0, Female, Male }
    export enum MaritalStatus { Option0, Single, Married }