/** 
* Module containing complex data types like HyperLink or ChoiceOption.
*
* This module is autogenerated from Sense/Net ContentRepository.
*
* ```
* let link = new Fields.HyperlinkData({
*   Href: 'http://sensenet.com',
*   Text: 'Link to sensenet.com',
*   Title: 'Go to sensenet.com',
*   Target: '_blank'
* });
*
* let webContent = new ContentTypes.WebContentDemo({
*   Id: 1,
*   Name: 'MyContent',
*   DisplayName: 'My Content',
*   Type: 'WebContentDemo',
*   Details: link 
* });
*
* ```
*/

export module Fields {
    export class HyperLink {
        Href: string;
        Text: string;
        Title: string;
        Target: string;
        constructor(href: string, text: string, title: string, target: string) {
            this.Href = href;
            this.Text = text;
            this.Title = title;
            this.Target = target;
        }
    }

    export class ChoiceOption {
        Value: string;
        Text: string;
        Enabled: boolean;
        Selected: boolean;

        constructor(value: string, text?: string, enabled?: boolean, selected?: boolean) {
            this.Value = value;
            this.Text = text;
            this.Enabled = enabled;
            this.Selected = selected;
        }
    }

    export class DeferredUriObject {
        uri: string;
    }

    export class DeferredObject extends Object {
        __deferred: DeferredUriObject;
    }

    export class MediaObject {
        edit_media: string;
        media_src: string;
        content_type: string;
        media_etag: string;
    }

    export class MediaResourceObject extends Object {
        __mediaresource: MediaObject;
    }
}