/**
 * @module Resources
 * @preferred
 * 
 * @description Module for Resource classes. Helps you to reach string resource classes with dot notation.
 *
 * This module is autogenerated from Sense/Net Localization files.
 * ```ts
 * import * as SenseNet from './Scripts/SenseNet'
 *
 * const editActionName = SenseNet.Resources.Actions["Edit"]
 * ```
 */ /** */

export class Ctd { }
export class CtdApplication { }
export class CtdApplicationOverride { }
export class CtdAspect { }
export class CtdContentLink { }
export class CtdContentList { }
export class CtdContentType { }
export class CtdCustomList { }
export class CtdCustomListItem { }
export class CtdDevice { }
export class CtdDomain { }
export class CtdDomains { }
export class CtdEmail { }
export class CtdExecutableFile { }
export class CtdExportToCsvApplication { }
export class CtdFieldSettingContent { }
export class CtdFile { }
export class CtdFolder { }
export class CtdGenericContent { }
export class CtdGenericODataApplication { }
export class CtdGroup { }
export class CtdHtmlTemplate { }
export class CtdHttpHandlerApplication { }
export class CtdHttpStatusApplication { }
export class CtdImage { }
export class CtdImageLibrary { }
export class CtdImgResizeApplication { }
export class CtdIndexingSettings { }
export class CtdItemList { }
export class CtdLibrary { }
export class CtdListItem { }
export class CtdLoggingSettings { }
export class CtdMemo { }
export class CtdMemoList { }
export class CtdOrganizationalUnit { }
export class CtdPortalRoot { }
export class CtdPortalSettings { }
export class CtdPreviewImage { }
export class CtdProfileDomain { }
export class CtdProfiles { }
export class CtdQuery { }
export class CtdResource { }
export class CtdResources { }
export class CtdRssApplication { }
export class CtdRuntimeContentContainer { }
export class CtdSettings { }
export class CtdSite { }
export class CtdSites { }
export class CtdSmartFolder { }
export class CtdSystemFile { }
export class CtdSystemFolder { }
export class CtdTask { }
export class CtdTaskList { }
export class CtdTrashBag { }
export class CtdTrashBin { }
export class CtdUser { }
export class CtdUserProfile { }
export class CtdWorkspace { }
export class Error_ContentRepository { }
export class Error_Portal { }
export class Error_Storage { }