/**
 * Module for Resource classes. Helps you to reach string resource classes with dot notation.
 *
 * This module is autogenerated from Sense/Net Localization files.
 * ```ts
 * import * as SenseNet from './Scripts/SenseNet'
 *
 * const editActionName = SenseNet.Resources.Actions["Edit"]
 * ```
 */

export module Resources {
    export class Actions { }
    export class ADSync { }
    export class Aspect { }
}